// User
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_LOGIN_VALID = 'SET_LOGIN_VALID';
export const SET_USER_SIGN_STATUS = 'SET_USER_SIGN_STATUS';
export const SET_USER_PLAYLISTS = 'SET_USER_PLAYLISTS';
export const UPDATE_USER_PLAYLIST = 'UPDATE_USER_PLAYLIST';
export const SUBSCRIBE_PLAYLIST = 'SUBSCRIBE_PLAYLIST';
export const UNSUBSCRIBE_PLAYLIST = 'UNSUBSCRIBE_PLAYLIST';
export const SET_USER_ALBUMS = 'SET_USER_ALBUMS';
export const SUBSCRIBE_ALBUM = 'SUBSCRIBE_ALBUM';
export const UNSUBSCRIBE_ALBUM = 'UNSUBSCRIBE_ALBUM';
export const SET_USER_ARTISTS = 'SET_USER_ARTISTS';
export const SUBSCRIBE_ARTIST = 'SUBSCRIBE_ARTIST';
export const UNSUBSCRIBE_ARTIST = 'UNSUBSCRIBE_ARTIST';
export const SET_USER_VIDEOS = 'SET_USER_VIDEOS';
export const SUBSCRIBE_VIDEO = 'SUBSCRIBE_VIDEO';
export const UNSUBSCRIBE_VIDEO = 'UNSUBSCRIBE_VIDEO';

// UI
export const UPDATE_PLAYING_URL = 'UPDATE_PLAYING_URL';
export const PAUSE_PLAYING_MUSIC = 'PAUSE_PLAYING_MUSIC';
export const RESUME_PLAYING_MUSIC = 'RESUME_PLAYING_MUSIC';
export const SET_ACTIVE_LYRIC = 'SET_ACTIVE_LYRIC';
export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SHOW_COLLECT_POPUP = 'SHOW_COLLECT_POPUP';
export const HIDE_COLLECT_POPUP = 'HIDE_COLLECT_POPUP';
export const SET_COLLECT_TRACKS = 'SET_COLLECT_TRACKS';
export const SET_UI_FAV_ALBUM = 'SET_UI_FAV_ALBUM';
export const SET_UI_FAV_ARTIST = 'SET_UI_FAV_ARTIST';
export const SET_UI_FAV_VIDEO = 'SET_UI_FAV_VIDEO';
export const SET_UI_TEMP_PLAYLIST = 'SET_UI_TEMP_PLAYLIST';
export const SET_UI_TEMP_RELATED_PLAYLISTS = 'SET_UI_TEMP_RELATED_PLAYLISTS';
export const SET_UI_TEMP_ALBUM = 'SET_UI_TEMP_ALBUM';
export const SET_UI_TEMP_RELATED_ALBUMS = 'SET_UI_TEMP_RELATED_ALBUMS';
export const SET_UI_TEMP_ARTIST = 'SET_UI_TEMP_ARTIST';
export const SET_UI_TEMP_VIDEO = 'SET_UI_TEMP_VIDEO';
export const SET_UI_RECOMMEND_SONGS = 'SET_UI_RECOMMEND_SONGS';
export const SET_UI_RECOMMEND_STATISTICS = 'SET_UI_RECOMMEND_STATISTICS';

// Playlist
export const SET_PLAY_LIST = 'SET_PLAY_LIST';
export const CLEAR_PLAY_LIST = 'CLEAR_PLAY_LIST';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const SET_LOOP_MODE_LIST = 'SET_LOOP_MODE_LOOP';
export const SET_LOOP_MODE_SINGLE = 'SET_LOOP_MODE_SINGLE';
export const SET_LOOP_MODE_RANDOM = 'SET_LOOP_MODE_RANDOM';
export const RESTORE_PLAYLIST = 'RESTORE_PLAYLIST';
export const INSERT_TRACK_INTO_PLAYLIST = 'INSERT_TRACK_INTO_PLAYLIST';

// Settings
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
