export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_LOGIN_VALID = 'SET_LOGIN_VALID';
export const SET_USER_PLAYLISTS = 'SET_USER_PLAYLISTS';
export const UPDATE_USER_PLAYLIST = 'UPDATE_USER_PLAYLIST';

export const UPDATE_PLAYING_URL = 'UPDATE_PLAYING_URL';
export const PAUSE_PLAYING_MUSIC = 'PAUSE_PLAYING_MUSIC';
export const RESUME_PLAYING_MUSIC = 'RESUME_PLAYING_MUSIC';

export const SET_PLAY_LIST = 'SET_PLAY_LIST';
export const CLEAR_PLAY_LIST = 'CLEAR_PLAY_LIST';
export const SET_ACTIVE_LYRIC = 'SET_ACTIVE_LYRIC';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const SET_LOOP_MODE_LOOP = 'SET_LOOP_MODE_LOOP';
export const SET_LOOP_MODE_SINGLE = 'SET_LOOP_MODE_SINGLE';
export const SET_LOOP_MODE_RANDOM = 'SET_LOOP_MODE_RANDOM';
export const RESTORE_PLAYLIST = 'RESTORE_PLAYLIST';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const WRITE_SETTINGS = 'WRITE_SETTINGS';
