export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER';
export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER';

export const UPDATE_USER_COOKIES = 'UPDATE_USER_COOKIES';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const SET_LOGIN_VALID = 'SET_LOGIN_VALID';

export const SET_PLAYING_MUSIC = 'SET_PLAYING_MUSIC';
export const CLEAR_PLAYING_MUSIC = 'CLEAR_PLAYING_MUSIC';
export const PAUSE_PLAYING_MUSIC = 'PAUSE_PLAYING_MUSIC';
export const RESUME_PLAYING_MUSIC = 'RESUME_PLAYING_MUSIC';
