// User
export const SET_LOGIN_VALID = 'SET_LOGIN_VALID';
export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_SIGN_PENDING = 'SET_USER_SIGN_PENDING';
export const SET_USER_SIGN_STATUS = 'SET_USER_SIGN_STATUS';
export const SET_USER_FAVOR_TRACKS = 'SET_USER_FAVOR_TRACKS';
export const SET_USER_PLAYLISTS = 'SET_USER_PLAYLISTS';
export const UPDATE_USER_PLAYLIST = 'UPDATE_USER_PLAYLIST';
export const SUBSCRIBE_PLAYLIST = 'SUBSCRIBE_PLAYLIST';
export const UNSUBSCRIBE_PLAYLIST = 'UNSUBSCRIBE_PLAYLIST';
export const SET_USER_ALBUMS = 'SET_USER_ALBUMS';
export const SUBSCRIBE_ALBUM = 'SUBSCRIBE_ALBUM';
export const UNSUBSCRIBE_ALBUM = 'UNSUBSCRIBE_ALBUM';
export const SET_USER_ARTISTS = 'SET_USER_ARTISTS';
export const SUBSCRIBE_ARTIST = 'SUBSCRIBE_ARTIST';
export const UNSUBSCRIBE_ARTIST = 'UNSUBSCRIBE_ARTIST';
export const SET_USER_VIDEOS = 'SET_USER_VIDEOS';
export const SUBSCRIBE_VIDEO = 'SUBSCRIBE_VIDEO';
export const UNSUBSCRIBE_VIDEO = 'UNSUBSCRIBE_VIDEO';
export const SET_USER_DJ_RADIOS = 'SET_USER_DJ_RADIOS';
export const SUBSCRIBE_DJ_RADIO = 'SUBSCRIBE_DJ_RADIO';
export const UNSUBSCRIBE_DJ_RADIO = 'UNSUBSCRIBE_DJ_RADIO';

// UI
export const RESTORE_UI_STATE = 'RESTORE_UI_STATE';
export const UPDATE_PLAYING_URL = 'UPDATE_PLAYING_URL';
export const SET_AUDIO_VOLUME = 'SET_AUDIO_VOLUME';
export const SET_AUDIO_PAUSED = 'SET_AUDIO_PAUSED';
export const SET_LYRIC_LOADING = 'SET_LYRIC_LOADING';
export const SET_ACTIVE_LYRIC = 'SET_ACTIVE_LYRIC';
export const SET_SEARCH_PARAM = 'SET_SEARCH_PARAM';
export const SET_SEARCH_PENDING = 'SET_SEARCH_PENDING';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';
export const SHOW_COLLECT_POPUP = 'SHOW_COLLECT_POPUP';
export const HIDE_COLLECT_POPUP = 'HIDE_COLLECT_POPUP';
export const SET_COLLECT_TRACKS = 'SET_COLLECT_TRACKS';

// Playlist
export const SET_PLAY_LIST = 'SET_PLAY_LIST';
export const CLEAR_PLAY_LIST = 'CLEAR_PLAY_LIST';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const SET_LOOP_MODE_LIST = 'SET_LOOP_MODE_LOOP';
export const SET_LOOP_MODE_SINGLE = 'SET_LOOP_MODE_SINGLE';
export const SET_LOOP_MODE_RANDOM = 'SET_LOOP_MODE_RANDOM';
export const RESTORE_PLAYLIST = 'RESTORE_PLAYLIST';
export const INSERT_TRACK_INTO_PLAYLIST = 'INSERT_TRACK_INTO_PLAYLIST';
export const REMOVE_TRACK_FROM_PLAYLIST = 'REMOVE_TRACK_FROM_PLAYLIST';

// Settings
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

// Radio
export const ACTIVATE_RADIO = 'ACTIVATE_RADIO';
export const CLEAR_RADIO = 'CLEAR_RADIO';
export const APPEND_RADIO = 'APPEND_RADIO';
export const REMOVE_RADIO = 'REMOVE_RADIO';
export const SET_RADIO_INDEX = 'SET_RADIO_INDEX';
export const RESTORE_RADIO = 'RESTORE_RADIO';

// Recommend
export const SET_RECOMMEND_SONGS = 'SET_RECOMMEND_SONGS';
export const SET_RECOMMEND_STATISTICS = 'SET_RECOMMEND_STATISTICS';
export const REPLACE_RECOMMEND_SONG = 'REPLACE_RECOMMEND_SONG';
