name: Release

on:
  push:
    tags: ["**"]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn

      - name: Build
        run: |
          yarn install
          script/ci-build.sh tag

      - name: Upload asar
        uses: actions/upload-artifact@v3
        with:
          name: asar
          path: build/*.asar
