# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Yarn CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn
    - run: yarn dist
    - run: yarn build linux
    - run: yarn build darwin
    - run: yarn build asar

    - name: Upload Linux outs
      uses: actions/upload-artifact@v2
      with:
          name: app-debug-linux ${{ matrix.node-version }}
          path: build/Electron NCM-linux-x64
     
    - name: Upload Darwin outs
      uses: actions/upload-artifact@v2
      with:
          name: app-debug-darwin ${{ matrix.node-version }}
          path: build/Electron NCM-darwin-x64
    - name: Upload Asar outs
      uses: actions/upload-artifact@v2
      with:
          name: app-debug-asar ${{ matrix.node-version }}
          path: build/Electron NCM-darwin-x64
